/*
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms
 * By starting with 1 and 2, the first 10 terms will be: 1,2,3,5,8,13,21,34,55,89,...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million
 * find the sum of the even-valued terms
 *
 * */
#include <iostream>

int sum_even_fib(int N) {
  int sum = 0;
  int a = 1, b = 2;
  while (b <= N) {
      if (b % 2 == 0) {
        sum += b;  
      }
      int next = a + b;
      a = b;
      b = next;
  }
  return sum;
}

int main(){
  int N = 4000000;
  int find_sum = sum_even_fib(N);
  printf("\nsum = %d\n", find_sum);  
  return 0;
}
